name: Trivy Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  scan:
    name: Scan Terraform with Trivy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'CRITICAL,HIGH'